org.gradle.jvmargs=-Xmx4G -Djava.net.preferIPv4Stack=true
org.gradle.daemon=false
org.gradle.parallel=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.252
neo_version_range=[21.1,)
neo_form_version=1.21.1-20240808.144430
loader_version_range=[1,)

mod_id=drg_flares
mod_name=DRG Flares
mod_license=custom
mod_version=1.3.0
mod_group_id=me.shirkneko.drgflares
mod_authors=LizardOfOz
mod_description=Adds Flares from Deep Rock Galactic

cloth_config_version=16.0.143
