pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'net.neoforged.moddev' version '2.0.148' apply false
}

rootProject.name = 'drg_flares'
include 'common', 'neoforge'
