modLoader = "javafml"
loaderVersion = "[1,)"
license = "custom"
issueTrackerURL = "https://github.com/Lizard-Of-Oz/DRG_Flares"

[[mods]]
modId = "drg_flares"
version = "1.2.8"
displayName = "DRG Flares"
authors = "LizardOfOz"
description = "Adds Flares from Deep Rock Galactic"
logoFile = "icon.png"
displayURL = "https://github.com/Lizard-Of-Oz/DRG_Flares"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.drg_flares]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drg_flares]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"
